branches:
  - main

plugins:
  - - '@semantic-release/commit-analyzer'
    - releaseRules:
        - type: refactor
          release: patch
        - type: chore
          release: patch
  - '@semantic-release/github'
