name: commit

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: docker-compose up -d &
      - run: pnpm install
      - run: pnpm run check
      - run: pnpm run build
      - run: pnpm run migrate up
      - run: pnpm run test
      - run: pnpm run test:e2e

  release:
    needs: [gitleaks, lint-dockerfile, test]
    runs-on: ubuntu-latest
    steps:
      - uses: joaofnds/semantic-release-action@v1.1.0
        with:
          plugins: 'conventional-changelog-conventionalcommits'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
