name: commit

on:
  push:
    branches: [main]
    paths-ignore: ['README.md']
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hadolint/hadolint-action@v3.2.0

  test:
    runs-on: ubuntu-latest
    env:
      CONFIG_PATH: src/config/test.yaml
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
      - run: docker compose up -d &
      - run: corepack enable
      - run: pnpm install
      - run: pnpm run check
      - run: pnpm run build
      - run: pnpm run migrate up
      - run: pnpm run test
      - run: pnpm run test:e2e

  release:
    needs: [gitleaks, lint-dockerfile, test]
    runs-on: ubuntu-latest
    steps:
      - uses: joaofnds/semantic-release-action@v1.4.0
        with:
          plugins: conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
